AWSTemplateFormatVersion: 2010-09-09
Description: BuildBuckets Template.
  This creates Build S3 Buckets. These buckets hold artifacts used and/or created by Build Pipelines or the ImageBuilder.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - AccountAlias
          - EnvironmentName
      - Label:
          default: Bucket Configuration
        Parameters:
          - UseGlacier
    ParameterLabels:
      AccountAlias:
        default: Account Alias
      EnvironmentName:
        default: Environment Name
      UseGlacier:
        default: Use Glacier
Parameters:
  AccountAlias:
    Description: Unique Alias of the Account (if defined). If specified, the Alias instead of the AccountID is appended to bucket names to insure uniqueness.
    Type: String
    MaxLength: 32
    Default: ''
    AllowedPattern: (^$|^[a-z][-a-z0-9]*$)
    ConstraintDescription: must begin with a lower case letter and contain lower case letters, numbers and dashes.
  EnvironmentName:
    Description: Name of the Environment associated with the Stack
    Type: String
    Default: Production
    AllowedValues:
      - Jumpstart
      - Build
      - Production
      - Development
    ConstraintDescription: must be Jumpstart, Build, Production or Development.
  UseGlacier:
    Description: Use Glacier for Archived Logs
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    ConstraintDescription: must be either true or false.
Conditions:
  AppendAccountId: !Equals [ !Ref AccountAlias, '' ]
  ConfigureGlacier: !Equals [ !Ref UseGlacier, true ]
Resources:
  ImageBuilderLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
        - imagebuilder-logs-${Account}-${AWS::Region}
        - Account: !If [ AppendAccountId, !Ref 'AWS::AccountId', !Ref AccountAlias ]
      AccessControl: LogDeliveryWrite
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ReduceStorageCostsThenDeletePriorVersions
            Status: Enabled
            Prefix: ''
            Transitions:
              - StorageClass: !If [ ConfigureGlacier, GLACIER, STANDARD_IA ]
                TransitionInDays: 90
            ExpirationInDays: 2555
            NoncurrentVersionTransitions:
              - StorageClass: !If [ ConfigureGlacier, GLACIER, STANDARD_IA ]
                TransitionInDays: 90
            NoncurrentVersionExpirationInDays: 2555
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ImageBuilderLogsBucket
    DeletionPolicy: Retain
#  ImageBuilderLogsBucketPolicy:
#    Type: AWS::S3::BucketPolicy
#    Properties:
#      Bucket: !Ref ImageBuilderLogsBucket
#      PolicyDocument:
#        Version: 2012-10-17
#        Statement:
#          - Sid: DenyUnEncryptedConnections
#            Effect: Deny
#            Principal:
#              AWS: '*'
#            Action: s3:*
#            Resource: !Sub arn:aws:s3:::${ImageBuilderLogsBucket}/*
#            Condition:
#              Bool:
#                aws:SecureTransport: false
#          - Sid: DenyUnEncryptedObjectUploads
#            Effect: Deny
#            Principal:
#              AWS: '*'
#            Action: s3:PutObject
#            Resource: !Sub arn:aws:s3:::${ImageBuilderLogsBucket}/*
#            Condition:
#              StringNotEquals:
#                s3:x-amz-server-side-encryption: AES256
#          - Sid: DenyDeletes
#            Effect: Deny
#            Principal:
#              AWS: '*'
#            Action: s3:Delete*
#            Resource: !Sub arn:aws:s3:::${ImageBuilderLogsBucket}/*
#          - Sid: DenyDeleteBucket
#            Effect: Deny
#            Principal:
#              AWS: '*'
#            Action: s3:DeleteBucket
#            Resource: !Sub arn:aws:s3:::${ImageBuilderLogsBucket}
#    DependsOn: ImageBuilderLogsBucket
  ComponentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
        - components-${Account}-${AWS::Region}
        - Account: !If [ AppendAccountId, !Ref 'AWS::AccountId', !Ref AccountAlias ]
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ReduceStorageCostsThenDeletePriorVersions
            Status: Enabled
            Prefix: ''
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
            ExpirationInDays: 425
            NoncurrentVersionTransitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
            NoncurrentVersionExpirationInDays: 395
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ComponentsBucket
    DeletionPolicy: Retain
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
        - artifacts-${Account}-${AWS::Region}
        - Account: !If [ AppendAccountId, !Ref 'AWS::AccountId', !Ref AccountAlias ]
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ReduceStorageCostsThenDeletePriorVersions
            Status: Enabled
            Prefix: ''
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
            ExpirationInDays: 425
            NoncurrentVersionTransitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
            NoncurrentVersionExpirationInDays: 395
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ArtifactsBucket
    DeletionPolicy: Retain
Outputs:
  ImageBuilderLogsBucket:
    Description: The ImageBuilder Logs Bucket Name
    Value: !Ref ImageBuilderLogsBucket
    Export:
      Name: !Sub ${AWS::StackName}-ImageBuilderLogsBucket
  ComponentsBucket:
    Description: The Components Bucket Name
    Value: !Ref ComponentsBucket
    Export:
      Name: !Sub ${AWS::StackName}-ComponentsBucket
  ArtifactsBucket:
    Description: The Artifacts Bucket Name
    Value: !Ref ArtifactsBucket
    Export:
      Name: !Sub ${AWS::StackName}-ArtifactsBucket
