AWSTemplateFormatVersion: 2010-09-09
Description: Components Template.
  This creates ImageBuilder Components. These Components are used for Building new AMIs.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Stack Dependencies
        Parameters:
          - BuildBucketsStackName
      - Label:
          default: Component Configuration
        Parameters:
          - HelloWorldLinuxComponentS3Key
          - HelloWorldWindowsComponentS3Key
    ParameterLabels:
      BuildBucketsStackName:
        default: BuildBuckets Stack Name
      HelloWorldLinuxComponentS3Key:
        default: HelloWorldLinux Component S3 Key
      HelloWorldWindowsComponentS3Key:
        default: HelloWorldWindows Component S3 Key
Parameters:
  BuildBucketsStackName:
    Description: Name of the CloudFormation Stack containing Build Buckets
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: BuildBuckets
    AllowedPattern: ^[A-Z][-a-zA-Z0-9]*$
    ConstraintDescription: must begin with an upper case letter and contain alphanumeric characters and dashes.
  HelloWorldLinuxComponentS3Key:
    Description: Key of Object within the S3 Bucket containing the HelloWorldLinux Component document
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: HelloWorldLinux.yaml
    AllowedPattern: ^HelloWorldLinux(\/[0-9a-f]{32})?\.yaml$
    ConstraintDescription: must be HelloWorldLinux.yaml, or HelloWorldLinux/<md5_hash>.yaml.
  HelloWorldWindowsComponentS3Key:
    Description: Key of Object within the S3 Bucket containing the HelloWorldWindows Component document
    Type: String
    MinLength: 2
    MaxLength: 64
    Default: HelloWorldWindows.yaml
    AllowedPattern: ^HelloWorldWindows(\/[0-9a-f]{32})?\.yaml$
    ConstraintDescription: must be HelloWorldWindows.yaml, or HelloWorldWindows/<md5_hash>.yaml.
Resources:
  HelloWorldLinuxComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: HelloWorldLinux
      Description: This is a variant of the HelloWorld Sample component, which uses a constant for the Greeting.
      Platform: Linux
      Version: '0.0.1'
      ChangeDescription: Initial version
      Uri: !Sub
        - s3://${S3Bucket}/${HelloWorldLinuxComponentS3Key}
        - S3Bucket: !ImportValue
            Fn::Sub: ${BuildBucketsStackName}-ComponentsBucket
      Tags:
        Name: HelloWorldLinux
  HelloWorldWindowsComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: HelloWorldWindows
      Description: This is a variant of the HelloWorld Sample component, which uses a constant for the Greeting.
      Platform: Windows
      Version: '0.0.1'
      ChangeDescription: Initial version
      Uri: !Sub
        - s3://${S3Bucket}/${HelloWorldWindowsComponentS3Key}
        - S3Bucket: !ImportValue
            Fn::Sub: ${BuildBucketsStackName}-ComponentsBucket
      Tags:
        Name: HelloWorldWindows
Outputs:
  HelloWorldLinuxComponentArn:
    Description: The HelloWorldLinux Component Arn
    Value: !Ref HelloWorldLinuxComponent
    Export:
      Name: !Sub ${AWS::StackName}-HelloWorldLinuxComponentArn
  HelloWorldWindowsComponentArn:
    Description: The HelloWorldWindows Component Arn
    Value: !Ref HelloWorldWindowsComponent
    Export:
      Name: !Sub ${AWS::StackName}-HelloWorldWindowsComponentArn
